BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[BussPart] (
    [BussPartID] INT NOT NULL IDENTITY(1,1),
    [BpName] NVARCHAR(1000) NOT NULL,
    [BpCode] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [BussPart_pkey] PRIMARY KEY CLUSTERED ([BussPartID])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
